### PR TITLE
ci: configure sem release monorepo

### PR DESCRIPTION
**Pull request by edgarmueller**
worked for my toy example, let's see if it does the trick here as well

### CODE REVIEW

**Review by ottovw — APPROVED** [review]

**Comment by ottovw** [comment]
what does this achieve? approved anyways ...

**Comment by edgarmueller** [comment]
It should only consider commits for generating the changelog/release that actually affect one of the packages, see https://github.com/kittgen/kittgen-nestjs/releases/tag/nestjs-https-redirect-v1.0.0 for example

**Pull request merged**
